/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LolSummonersPuuidOverviewIndexRouteImport } from './routes/lol/summoners/$puuid/overview/index'
import { Route as LolSummonersPuuidLiveGameIndexRouteImport } from './routes/lol/summoners/$puuid/live-game/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LolSummonersPuuidOverviewIndexRoute =
  LolSummonersPuuidOverviewIndexRouteImport.update({
    id: '/lol/summoners/$puuid/overview/',
    path: '/lol/summoners/$puuid/overview/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LolSummonersPuuidLiveGameIndexRoute =
  LolSummonersPuuidLiveGameIndexRouteImport.update({
    id: '/lol/summoners/$puuid/live-game/',
    path: '/lol/summoners/$puuid/live-game/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lol/summoners/$puuid/live-game/': typeof LolSummonersPuuidLiveGameIndexRoute
  '/lol/summoners/$puuid/overview/': typeof LolSummonersPuuidOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lol/summoners/$puuid/live-game': typeof LolSummonersPuuidLiveGameIndexRoute
  '/lol/summoners/$puuid/overview': typeof LolSummonersPuuidOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lol/summoners/$puuid/live-game/': typeof LolSummonersPuuidLiveGameIndexRoute
  '/lol/summoners/$puuid/overview/': typeof LolSummonersPuuidOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lol/summoners/$puuid/live-game/'
    | '/lol/summoners/$puuid/overview/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lol/summoners/$puuid/live-game' | '/lol/summoners/$puuid/overview'
  id:
    | '__root__'
    | '/'
    | '/lol/summoners/$puuid/live-game/'
    | '/lol/summoners/$puuid/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LolSummonersPuuidLiveGameIndexRoute: typeof LolSummonersPuuidLiveGameIndexRoute
  LolSummonersPuuidOverviewIndexRoute: typeof LolSummonersPuuidOverviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/summoners/$puuid/overview/': {
      id: '/lol/summoners/$puuid/overview/'
      path: '/lol/summoners/$puuid/overview'
      fullPath: '/lol/summoners/$puuid/overview/'
      preLoaderRoute: typeof LolSummonersPuuidOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/summoners/$puuid/live-game/': {
      id: '/lol/summoners/$puuid/live-game/'
      path: '/lol/summoners/$puuid/live-game'
      fullPath: '/lol/summoners/$puuid/live-game/'
      preLoaderRoute: typeof LolSummonersPuuidLiveGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LolSummonersPuuidLiveGameIndexRoute: LolSummonersPuuidLiveGameIndexRoute,
  LolSummonersPuuidOverviewIndexRoute: LolSummonersPuuidOverviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
